In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('Pintu ML.csv')

In [3]:
df

,age,gender,activity_level,alcohol_smoke_both,stress,diet,height,weight,heartrate,BP,daily_step_goal,daily_caloric_intake
0,56,female,lightly_active,none,moderate,low_carb,189.85,51.58,65,113/61,8000,1734.373437
1,46,female,lightly_active,alcohol,high,vegetarian,167.32,60.34,79,100/85,8000,1729.956250
2,32,female,moderately_active,alcohol,low,balanced,188.72,51.84,72,133/81,10000,2134.195000
3,60,male,sedentary,smoke,high,balanced,163.12,119.29,100,140/69,6000,2300.880000
4,25,male,lightly_active,both,moderate,vegetarian,166.43,69.52,82,106/65,8000,2221.157813
...,...,...,...,...,...,...,...,...,...,...,...,...
3995,57,male,lightly_active,smoke,moderate,low_carb,196.09,105.34,95,116/85,8000,2748.573438
3996,20,female,lightly_active,none,high,vegetarian,158.93,64.09,94,126/61,8000,1888.167187
3997,46,female,very_active,none,moderate,low_carb,164.78,83.95,83,115/73,12000,2550.196875
3998,58,female,sedentary,both,moderate,low_carb,198.79,92.52,74,92/72,6000,2059.965000
3999,46,female,sedentary,both,low,high_protein,168.56,61.21,70,120/61,6000,1529.520000

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   age                   4000 non-null   int64
 1   gender                4000 non-null   object
 2   activity_level        4000 non-null   object
 3   alcohol_smoke_both    4000 non-null   object
 4   stress                4000 non-null   object
 5   diet                  4000 non-null   object
 6   height                4000 non-null   float64
 7   weight                4000 non-null   float64
 8   heartrate             4000 non-null   int64
 9   BP                    4000 non-null   object
 10  daily_step_goal       4000 non-null   int64
 11  daily_caloric_intake  4000 non-null   float64
dtypes: float64(3), int64(3), object(6)
memory usage: 375.1+ KB
None

In [5]:
df = df.applymap(lambda x: int(x) if isinstance(x, float) else x)

In [6]:
df

,age,gender,activity_level,alcohol_smoke_both,stress,diet,height,weight,heartrate,BP,daily_step_goal,daily_caloric_intake
0,56,female,lightly_active,none,moderate,low_carb,189,51,65,113/61,8000,1734
1,46,female,lightly_active,alcohol,high,vegetarian,167,60,79,100/85,8000,1729
2,32,female,moderately_active,alcohol,low,balanced,188,51,72,133/81,10000,2134
3,60,male,sedentary,smoke,high,balanced,163,119,100,140/69,6000,2300
4,25,male,lightly_active,both,moderate,vegetarian,166,69,82,106/65,8000,2221
...,...,...,...,...,...,...,...,...,...,...,...,...
3995,57,male,lightly_active,smoke,moderate,low_carb,196,105,95,116/85,8000,2748
3996,20,female,lightly_active,none,high,vegetarian,158,64,94,126/61,8000,1888
3997,46,female,very_active,none,moderate,low_carb,164,83,83,115/73,12000,2550
3998,58,female,sedentary,both,moderate,low_carb,198,92,74,92/72,6000,2059
3999,46,female,sedentary,both,low,high_protein,168,61,70,120/61,6000,1529

In [7]:
def calculate_ideal_sleep_duration(age, activity_level, stress, heartrate):
    sleep_duration = 7.5
    
    if age < 25:
        sleep_duration += 0.5
    elif age > 50:
        sleep_duration -= 0.5
    
    if activity_level == 'very_active':
        sleep_duration += 0.5
    elif activity_level == 'sedentary':
        sleep_duration -= 0.5
    
    if stress == 'high':
        sleep_duration += 0.5
    elif stress == 'low':
        sleep_duration -= 0.5
    
    if heartrate > 80:
        sleep_duration += 0.5
    
    return min(max(sleep_duration, 6), 9)

In [8]:
# Assuming df is your existing DataFrame
ideal_sleep_duration = [
    calculate_ideal_sleep_duration(df.at[i, 'age'], df.at[i, 'activity_level'], df.at[i, 'stress'], df.at[i, 'heartrate']) 
    for i in range(len(df))
]


df['ideal_sleep_duration'] = ideal_sleep_duration

In [9]:
features = df.drop(columns=['daily_caloric_intake', 'daily_step_goal', 'ideal_sleep_duration'])
targets = df[['daily_caloric_intake', 'daily_step_goal', 'ideal_sleep_duration']]

In [10]:
features.fillna(features.mode().iloc[0], inplace=True)
targets.fillna(targets.mode().iloc[0], inplace=True)

C:\Users\Harsha\AppData\Local\Temp\ipykernel_37584\2605496604.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  targets.fillna(targets.mode().iloc[0], inplace=True)

In [24]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder,OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
import joblib

In [12]:
X_train, X_test, y_train, y_test = train_test_split(features, targets, test_size=0.2, random_state=42)

In [13]:
df.head(1)

,age,gender,activity_level,alcohol_smoke_both,stress,diet,height,weight,heartrate,BP,daily_step_goal,daily_caloric_intake,ideal_sleep_duration
0,56,female,lightly_active,none,moderate,low_carb,189,51,65,113/61,8000,1734,7.0

In [14]:
bp_split = df['BP'].str.split('/', expand=True)
df['systolic_bp'] = bp_split[0].astype(np.int32)
df['diastolic_bp'] = bp_split[1].astype(np.int32)

In [15]:
df.drop(columns=['BP'], inplace=True)

In [16]:
df

,age,gender,activity_level,alcohol_smoke_both,stress,diet,height,weight,heartrate,daily_step_goal,daily_caloric_intake,ideal_sleep_duration,systolic_bp,diastolic_bp
0,56,female,lightly_active,none,moderate,low_carb,189,51,65,8000,1734,7.0,113,61
1,46,female,lightly_active,alcohol,high,vegetarian,167,60,79,8000,1729,8.0,100,85
2,32,female,moderately_active,alcohol,low,balanced,188,51,72,10000,2134,7.0,133,81
3,60,male,sedentary,smoke,high,balanced,163,119,100,6000,2300,7.5,140,69
4,25,male,lightly_active,both,moderate,vegetarian,166,69,82,8000,2221,8.0,106,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,57,male,lightly_active,smoke,moderate,low_carb,196,105,95,8000,2748,7.5,116,85
3996,20,female,lightly_active,none,high,vegetarian,158,64,94,8000,1888,9.0,126,61
3997,46,female,very_active,none,moderate,low_carb,164,83,83,12000,2550,8.5,115,73
3998,58,female,sedentary,both,moderate,low_carb,198,92,74,6000,2059,6.5,92,72
3999,46,female,sedentary,both,low,high_protein,168,61,70,6000,1529,6.5,120,61

In [17]:
numeric_features = ['age', 'height', 'weight', 'heart_rate', 'systolic_bp', 'diastolic_bp']
categorical_features = ['diet', 'gender', 'activity_level','alcohol_smoke_both','stress']

In [18]:
import pandas as pd


def remove_outliers(df, columns):
    for col in columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]
    return df


numerical_cols = ['height', 'weight', 'heartrate', 'age', 'systolic_bp', 'diastolic_bp', 'daily_step_goal', 'daily_caloric_intake','ideal_sleep_duration']
df = remove_outliers(df, numerical_cols)

In [19]:
df

,age,gender,activity_level,alcohol_smoke_both,stress,diet,height,weight,heartrate,daily_step_goal,daily_caloric_intake,ideal_sleep_duration,systolic_bp,diastolic_bp
0,56,female,lightly_active,none,moderate,low_carb,189,51,65,8000,1734,7.0,113,61
1,46,female,lightly_active,alcohol,high,vegetarian,167,60,79,8000,1729,8.0,100,85
2,32,female,moderately_active,alcohol,low,balanced,188,51,72,10000,2134,7.0,133,81
3,60,male,sedentary,smoke,high,balanced,163,119,100,6000,2300,7.5,140,69
4,25,male,lightly_active,both,moderate,vegetarian,166,69,82,8000,2221,8.0,106,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,57,male,lightly_active,smoke,moderate,low_carb,196,105,95,8000,2748,7.5,116,85
3996,20,female,lightly_active,none,high,vegetarian,158,64,94,8000,1888,9.0,126,61
3997,46,female,very_active,none,moderate,low_carb,164,83,83,12000,2550,8.5,115,73
3998,58,female,sedentary,both,moderate,low_carb,198,92,74,6000,2059,6.5,92,72
3999,46,female,sedentary,both,low,high_protein,168,61,70,6000,1529,6.5,120,61

In [20]:
features = df.drop(columns=['daily_caloric_intake', 'daily_step_goal', 'ideal_sleep_duration'])
targets = df[['daily_caloric_intake', 'daily_step_goal', 'ideal_sleep_duration']]

In [21]:
X_train, X_test, y_train, y_test = train_test_split(features, targets, test_size=0.2, random_state=42)

In [22]:
numeric_features = ['age', 'height', 'weight', 'heartrate', 'systolic_bp', 'diastolic_bp']
categorical_features = ['diet', 'gender','alcohol_smoke_both','stress']
ordinal_encoder = ['activity_level']

In [26]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error
import joblib

In [27]:
numeric_features = ['age', 'height', 'weight', 'heartrate', 'systolic_bp', 'diastolic_bp']
categorical_features = ['diet', 'gender','alcohol_smoke_both','stress']
ordinal_encoder = ['activity_level']

In [28]:
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features),
        ('cat', OneHotEncoder(), categorical_features),
        ('ord', OrdinalEncoder(), ordinal_encoder),
    ])

In [29]:
model = RandomForestRegressor(n_estimators=100, random_state=42)

In [30]:
pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                           ('model', model)])

In [31]:
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)
mse = mean_squared_error(y_test, y_pred, multioutput='raw_values')
print(f'Mean Squared Errors: {mse}')

Mean Squared Errors: [2.85538971e+03 0.00000000e+00 2.03399812e-01]

In [32]:
param_grid = {
    'model__n_estimators': [50, 100, 200],
    'model__max_depth': [None, 10, 20, 30]
}

In [33]:
grid_search = GridSearchCV(pipeline, param_grid, cv=5, scoring='neg_mean_squared_error', verbose=2)
grid_search.fit(X_train, y_train)
best_model = grid_search.best_estimator_
joblib.dump(best_model, 'mymodel.pkl')

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV] END ......model__max_depth=None, model__n_estimators=50; total time=   2.5s
[CV] END ......model__max_depth=None, model__n_estimators=50; total time=   2.4s
[CV] END ......model__max_depth=None, model__n_estimators=50; total time=   2.4s
[CV] END ......model__max_depth=None, model__n_estimators=50; total time=   2.5s
[CV] END ......model__max_depth=None, model__n_estimators=50; total time=   2.6s
[CV] END .....model__max_depth=None, model__n_estimators=100; total time=   5.0s
[CV] END .....model__max_depth=None, model__n_estimators=100; total time=   5.6s
[CV] END .....model__max_depth=None, model__n_estimators=100; total time=   5.5s
[CV] END .....model__max_depth=None, model__n_estimators=100; total time=   5.0s
[CV] END .....model__max_depth=None, model__n_estimators=100; total time=   5.2s
[CV] END .....model__max_depth=None, model__n_estimators=200; total time=  10.9s
[CV] END .....model__max_depth=None, model__n_estimators=200; total time=  11.3s
[CV] END .....model__max_depth=None, model__n_estimators=200; total time=  11.3s
[CV] END .....model__max_depth=None, model__n_estimators=200; total time=  10.8s
[CV] END .....model__max_depth=None, model__n_estimators=200; total time=  10.4s
[CV] END ........model__max_depth=10, model__n_estimators=50; total time=   1.7s
[CV] END ........model__max_depth=10, model__n_estimators=50; total time=   2.0s
[CV] END ........model__max_depth=10, model__n_estimators=50; total time=   2.2s
[CV] END ........model__max_depth=10, model__n_estimators=50; total time=   2.3s
[CV] END ........model__max_depth=10, model__n_estimators=50; total time=   2.4s
[CV] END .......model__max_depth=10, model__n_estimators=100; total time=   4.9s
[CV] END .......model__max_depth=10, model__n_estimators=100; total time=   5.8s
[CV] END .......model__max_depth=10, model__n_estimators=100; total time=   6.0s
[CV] END .......model__max_depth=10, model__n_estimators=100; total time=   5.9s
[CV] END .......model__max_depth=10, model__n_estimators=100; total time=   5.6s
[CV] END .......model__max_depth=10, model__n_estimators=200; total time=  12.8s
[CV] END .......model__max_depth=10, model__n_estimators=200; total time=  13.6s
[CV] END .......model__max_depth=10, model__n_estimators=200; total time=  12.4s
[CV] END .......model__max_depth=10, model__n_estimators=200; total time=   9.2s
[CV] END .......model__max_depth=10, model__n_estimators=200; total time=   7.5s
[CV] END ........model__max_depth=20, model__n_estimators=50; total time=   2.9s
[CV] END ........model__max_depth=20, model__n_estimators=50; total time=   3.2s
[CV] END ........model__max_depth=20, model__n_estimators=50; total time=   3.0s
[CV] END ........model__max_depth=20, model__n_estimators=50; total time=   2.8s
[CV] END ........model__max_depth=20, model__n_estimators=50; total time=   2.8s
[CV] END .......model__max_depth=20, model__n_estimators=100; total time=   5.5s
[CV] END .......model__max_depth=20, model__n_estimators=100; total time=   6.0s
[CV] END .......model__max_depth=20, model__n_estimators=100; total time=   6.1s
[CV] END .......model__max_depth=20, model__n_estimators=100; total time=   5.9s
[CV] END .......model__max_depth=20, model__n_estimators=100; total time=   6.6s
[CV] END .......model__max_depth=20, model__n_estimators=200; total time=  12.0s
[CV] END .......model__max_depth=20, model__n_estimators=200; total time=  13.1s
[CV] END .......model__max_depth=20, model__n_estimators=200; total time=  14.0s
[CV] END .......model__max_depth=20, model__n_estimators=200; total time=  12.8s
[CV] END .......model__max_depth=20, model__n_estimators=200; total time=  13.9s
[CV] END ........model__max_depth=30, model__n_estimators=50; total time=   3.2s
[CV] END ........model__max_depth=30, model__n_estimators=50; total time=   4.0s
[CV] END ........model__max_depth=30, model__n_estimators=50; total time=   4.4s
[CV] END ........model__max_depth=30, model__n_estimators=50; total time=   4.1s
[CV] END ........model__max_depth=30, model__n_estimators=50; total time=   4.0s
[CV] END .......model__max_depth=30, model__n_estimators=100; total time=   6.6s
[CV] END .......model__max_depth=30, model__n_estimators=100; total time=   6.3s
[CV] END .......model__max_depth=30, model__n_estimators=100; total time=   5.9s
[CV] END .......model__max_depth=30, model__n_estimators=100; total time=   5.6s
[CV] END .......model__max_depth=30, model__n_estimators=100; total time=   5.7s
[CV] END .......model__max_depth=30, model__n_estimators=200; total time=  13.6s
[CV] END .......model__max_depth=30, model__n_estimators=200; total time=  11.5s
[CV] END .......model__max_depth=30, model__n_estimators=200; total time=  13.9s
[CV] END .......model__max_depth=30, model__n_estimators=200; total time=  15.9s
[CV] END .......model__max_depth=30, model__n_estimators=200; total time=  16.4s

['mymodel.pkl']

In [ ]:
!pip show scikit-learn

In [ ]:
!pip install sklearn2pmml

In [41]:
from sklearn2pmml import sklearn2pmml
from sklearn2pmml.pipeline import PMMLPipeline

In [42]:
best_model = grid_search.best_estimator_

In [43]:
pipeline = PMMLPipeline([
    ('preprocessor', preprocessor),
    ('model', best_model)
])

In [46]:
sklearn2pmml(pipeline, 'pintuMl.pmml', java_home='C:\Program Files\Java\jdk-21𝒏')

RuntimeError: Java is not installed, or the Java executable is not on system path